### PR TITLE
New equal with relative tolerance

### PR DESCRIPTION
**Pull request by natefoulk4**
Changed numerical_utilities.f90 to implement a relative tolerance. Corrected unit tests that the new equal broke.

### CODE REVIEW

**Comment by wsmorgan** [comment]
I'm pulling to run the unit tests now.

**Comment by wsmorgan** [comment]
@natefoulk4 I just ran the unit tests and everything looks good except the tests:

```
RESULT: symmetry.find_site_equivalencies | find_site_equivalencies_nSites | gfortran 
	31.15% success (31.15% common) in 621629.2470 ms

RESULT: symmetry.find_site_equivalencies | find_site_equivalencies_BasEq | gfortran 
	44.55% success (44.55% common) in 608253.8570 ms
```

Did you fix these and forget to push the updated test files?

**Comment by natefoulk4** [comment]
@wsmorgan No that is my bad. I had assumed that something was wrong with fortpy (it looked like it got stuck on test 3 for both my fork and the msg symlib), but that's not the case, it just took a while to run the tests. I'll fix these ones and make a new pull request

**Comment by wsmorgan** [comment]
Yeah, there is a single test case for that function that takes several minutes.

**Comment by natefoulk4** [comment]
@wsmorgan That should do it.

**Comment by wsmorgan** [comment]
@natefoulk4 I'm still seeing some of the `get_spaceGroup` tests fail.

**Comment by wsmorgan** [comment]
@glwhart We've fixed all the unit tests and the code now passes with 100% test coverage. It's ready to be pulled in whenever you feel like doing a code review.

**Comment by natefoulk4** [comment]
@glwhart  I've implemented the changes that we talked about.

**Pull request merged**
