### PR TITLE
Added an optional absolute tolerance to the calling interface for `minkowski_reduce_basis`.

### PR DESCRIPTION
**Pull request by wsmorgan**

### CODE REVIEW

**Comment by glwhart** [comment]
Instead of wrapping an unnecessary `real` in another `int`, why don't we just remove both? I doubt Absoft still has the bug (that was a long time ago).

**Comment by wsmorgan** [comment]
I can make that change but I won't be able to run the unit tests to figure out if that breaks anything (`fortpy` hasn't worked on my laptop since I upgraded OS's).

**Comment by glwhart** [comment]
Sounds good. We can run the unit tests after the pull. I'm not going to
take time right now---I'm too thick in the enumlib unittest updates.


Gus Hart
Professor, Physics and Astronomy
http://msg.byu.edu
Dean, Physical and Mathematical Sciences
http://cpms.byu.edu

**Comment by wsmorgan** [comment]
I made the change.

**Pull request merged**
